### ISSUE TITLE
Write BIOSI appendix

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/thesis#107]
Shouldn't take too long. Suggested structure by @drvinceknight:

![carbon](https://user-images.githubusercontent.com/26261131/104757143-972b5180-5754-11eb-98ff-55ab8283e7d3.png)

**Comment by drvinceknight** [comment]
Should [thesis/chapters/intro/tex/structure.tex](https://github.com/daffidwilde/thesis/blob/main/chapters/intro/tex/structure.tex) also include an arrow from C to A?

**Comment by daffidwilde** [comment]
Do you mean from A to C?

I was wondering if it even needed to be in the thesis. It's nice because then all of my papers/projects are in there, but it isn't really relevant to anything other than Appendix A.

**Comment by drvinceknight** [comment]
> Do you mean from A to C?

:+1:

> 
> I was wondering if it even needed to be in the thesis. It's nice because then all of my papers/projects are in there, but it isn't really relevant to anything other than Appendix A.

If you didn't get around to doing it I don't think that would be a disaster. It's a nice to have and is somewhat connected (to Appendix A) and a nice way to show that `matching` has been used elsewhere.

But as I said I would not put yourself under a huge amount of stress to complete it. You could even just include a structure and a brief opening paragraph saying that the "following structure" is for a paper where `matching` was used to ...
