### ISSUE TITLE
Should reflections and further work swap places?

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/thesis#123]
It's a bit of a *meh* way to end the thesis, and I can't (be bothered to) write a flashy sentence or paragraph to close it out.

Would it make more sense for reflections to come at the end, or does that mess with the flow of the conclusion? I'm inclined to believe the latter.

**Comment by drvinceknight** [comment]
I think finishing with further work (as is) is a nicer way :+1:

**Comment by daffidwilde** [comment]
Cool 👍
