### ISSUE TITLE
Fix a title

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/thesis#89]
The working title of "Understanding variability in the National Health Service" is nice but is that really what the thesis does? I think it would be nice to incorporate something about algorithm evaluation in the title.

Something to think about.

**Comment by daffidwilde** [comment]
Current frontrunners are of a similar form:

1. New methods in algorithm evaluation and cluster initialisation with applications to healthcare
2. Algorithm evaluation and its applications in healthcare modelling
3. Novel methods for algorithm evaluation with applications to clustering in healthcare settings

**Comment by drvinceknight** [comment]
> New methods in algorithm evaluation and cluster initialisation with applications to healthcare

I like all three but that one gets my vote. :+1:
