### ISSUE TITLE
Code snippets could be better-placed

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/thesis#90]
Comments from @gillardjw sparked discussion around where the code snippet explanation should go in the thesis. Currently, it's in the introduction as part of the "Software development and best practices" section (that has not been written yet)

Some thoughts:

- The purpose of the explanation is to help the reader to read the thesis, so should there be a "how to read this thesis" section in the introduction along with the chapter structure diagram?
- Both Geraint and Nikoleta have had similar sections in their theses, but it does kind of dilute the formality and mathematical-ness of the introduction
- Would it be better to keep this information back as an appendix or have it up front? My opinion is that it should be in the introduction so the reader needn't try to decipher the code blocks that do appear throughout the thesis and its appendices

**Comment by drvinceknight** [comment]
I like it in the introduction. 

Perhaps once the "Software development and best practices" section is written it'll be clearer as to its purpose. If a reader just skims the introduction they will see code and then it might indeed "dilute the mathematical-ness" (whether or not this is a worry is a whole other discussion) but I'd suggest that if they read the "Software development and best practices" section then it's clear that this particular subsection is just there to clarify to the reader how code will be displayed in the thesis.

Putting it in the appendix is akin to removing it so I'd strongly advise against doing that.

Software development is a big part of your (most) research. Your thesis/research does software to a high standard, having a section that highlights this and helps the reader is a good thing.

**Comment by daffidwilde** [comment]
Left where it is. Looks better with the rest of the introduction.
